# Site settings
title: rust.cologne
description: "Rust User Group in the area of Cologne/Bonn, Germany"
baseurl: ""
url: "http://rust.cologne"
twitter_username: rustcologne
github_username:  killercup
email: rust.cologne@gmail.com
google_maps_api_key: AIzaSyBkz492n9gf895Tfi12ikKVurgIHHOFmK4

# Build settings
permalink: "/:year/:month/:day/:title.html"
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "event"

# Content settings
future: true # we use dates for the actual meetup time, not the post publication time
timezone: "Europe/Berlin"
